# Generated by Django 5.0.6 on 2024-07-29 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours', models.PositiveIntegerField()),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('civil_id', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('category', models.CharField(choices=[('freelancer', 'Freelancer'), ('employee', 'Employee'), ('job_seeker', 'Job Seeker'), ('student', 'University/College Student'), ('passionate', 'Passionate')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentGateway_thawani.course')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paymentGateway_thawani.discountcode')),
            ],
        ),
        migrations.CreateModel(
            name='Sublevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('level_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentGateway_thawani.course')),
            ],
        ),
    ]
